### ISSUE TITLE
autoRotate  + cubemap not working on safari

### ISSUE THREAD

**Issue by felixqk** [mpetroff/pannellum#292]
I wrote our player using this example https://pannellum.org/documentation/examples/cube-map/, and enabled the "autoRotate" functions, it is working fine in chrome and firefox, but not showing on Safari on Mac, removing "autoRotate" can show correctly on safari.

Sample script:
=============
```javascript
<script>
pannellum.viewer('panorama', {
    "type": "cubemap",
    "cubeMap": [
        "/img/f33315e8b3d641f890762f75e9a1ad7a_skybox1.jpg",
        "/img/f33315e8b3d641f890762f75e9a1ad7a_skybox2.jpg",
        "/img/f33315e8b3d641f890762f75e9a1ad7a_skybox3.jpg",
        "/img/f33315e8b3d641f890762f75e9a1ad7a_skybox4.jpg",
        "/img/f33315e8b3d641f890762f75e9a1ad7a_skybox0.jpg",
        "/img/f33315e8b3d641f890762f75e9a1ad7a_skybox5.jpg",
    ],
    "autoLoad": true,
    "autoRotate": -2
});
</script>
```

**Comment by mpetroff** [comment]
What do you mean by "not showing"? Is there anything shown in the developer console? What version of Safari are you using?

I can't reproduce this using Safari 7.1.3 running on OS X 10.9.5.

**Comment by felixqk** [comment]
Hi, @mpetroff ,

    Thanks for your reply. the Safari developer console have the following error:
=====================
[Error] TypeError: undefined is not a function (evaluating ['Math.sign(-c.autoRotate)')]

[Error] TypeError: undefined is not a function (evaluating 'Math.sign(-c.autoRotate)')
	r (pannellum.js, 759:109)
	X (pannellum.js, 796)

=====================
 The issue is I cannot drag and view the panorama image, it freezed at one shot.

 I am using Safari 8.0.4 (10600.4.10.7) running on OS X 10.10.2. Some clients of ours also have the same issue, but I don't know their version yet.

I will update my safari and also test.

**Comment by felixqk** [comment]
Hi, Matthew,

   when I update my safari to 10.0.1, the autoRotate feature works. Do you have any ideas it is not working on 8.0.4?

Best,

**Comment by mpetroff** [comment]
I can't say for sure without an error message, but it's probably because of `Math.sign`, making this a duplicate of #272. It's already been fixed in the development copy.

**Comment by felixqk** [comment]
Got it, thanks, I will test if the development copy fixed the issues here.

**Comment by mpetroff** [comment]
I release Pannellum 2.3.1 yesterday, which includes the mentioned fix.
